"use server"

import { sql } from "@/lib/db"
import { getSession } from "@/lib/auth"
import { revalidatePath } from "next/cache"
import { followUpDefaults } from "@/lib/proposta-config"

export type ProposalStage = "reunioes" | "follow1" | "follow2" | "follow3" | "win" | "loss"
export type ProposalLead = { id:number; nome:string; data_reuniao:string; etapa:ProposalStage; follow1_mensagem:string; follow1_enviado:boolean; follow1_data:string|null; follow2_mensagem:string; follow2_enviado:boolean; follow2_data:string|null; follow3_mensagem:string; follow3_enviado:boolean; follow3_data:string|null; anotacoes:string; plano_fechado:string|null; motivo_loss:string|null; position:number; created_at:string; updated_at:string }

async function ensureTable() {
  await sql`CREATE TABLE IF NOT EXISTS pg_propostas_crm (id SERIAL PRIMARY KEY, nome VARCHAR(255) NOT NULL, data_reuniao DATE NOT NULL DEFAULT CURRENT_DATE, etapa VARCHAR(30) NOT NULL DEFAULT 'reunioes', follow1_mensagem TEXT NOT NULL, follow1_enviado BOOLEAN NOT NULL DEFAULT false, follow1_data DATE, follow2_mensagem TEXT NOT NULL, follow2_enviado BOOLEAN NOT NULL DEFAULT false, follow2_data DATE, follow3_mensagem TEXT NOT NULL, follow3_enviado BOOLEAN NOT NULL DEFAULT false, follow3_data DATE, anotacoes TEXT NOT NULL DEFAULT '', plano_fechado VARCHAR(100), motivo_loss TEXT, position INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT NOW(), updated_at TIMESTAMP NOT NULL DEFAULT NOW())`
}
async function adminOnly() { const { user } = await getSession(); if (!user || !(user.roles ?? [user.role]).map((r:string|null|undefined)=>(r||"").toLowerCase()).includes("admin")) throw new Error("Não autorizado") }
export async function getProposalLeads() { await adminOnly(); await ensureTable(); return await sql`SELECT * FROM pg_propostas_crm ORDER BY etapa, position, id` as ProposalLead[] }
export async function createProposalLead(nome:string, dataReuniao:string) { await adminOnly(); await ensureTable(); const link = "https://progrowth-global.com/proposta?n=" + encodeURIComponent(nome.trim().split(/\s+/)[0]); const replace = (s:string) => s.replaceAll("{nome}", nome.trim().split(/\s+/)[0]).replaceAll("{link}", link); const rows = await sql`INSERT INTO pg_propostas_crm (nome,data_reuniao,follow1_mensagem,follow2_mensagem,follow3_mensagem) VALUES (${nome.trim()},${dataReuniao},${replace(followUpDefaults[0])},${replace(followUpDefaults[1])},${replace(followUpDefaults[2])}) RETURNING *`; revalidatePath("/propostas"); return rows[0] as ProposalLead }
export async function updateProposalLead(id:number, data:Partial<ProposalLead>) { await adminOnly(); await ensureTable(); const current = await sql`SELECT * FROM pg_propostas_crm WHERE id=${id}`; if (!current[0]) throw new Error("Lead não encontrado"); const row = {...current[0], ...data}; const rows = await sql`UPDATE pg_propostas_crm SET nome=${row.nome}, data_reuniao=${row.data_reuniao}, etapa=${row.etapa}, follow1_mensagem=${row.follow1_mensagem}, follow1_enviado=${row.follow1_enviado}, follow1_data=${row.follow1_data || null}, follow2_mensagem=${row.follow2_mensagem}, follow2_enviado=${row.follow2_enviado}, follow2_data=${row.follow2_data || null}, follow3_mensagem=${row.follow3_mensagem}, follow3_enviado=${row.follow3_enviado}, follow3_data=${row.follow3_data || null}, anotacoes=${row.anotacoes || ""}, plano_fechado=${row.plano_fechado || null}, motivo_loss=${row.motivo_loss || null}, position=${row.position || 0}, updated_at=NOW() WHERE id=${id} RETURNING *`; revalidatePath("/propostas"); return rows[0] as ProposalLead }
export async function deleteProposalLead(id:number) { await adminOnly(); await ensureTable(); await sql`DELETE FROM pg_propostas_crm WHERE id=${id}`; revalidatePath("/propostas") }
export async function getProposalTemplates() { await adminOnly(); return followUpDefaults }
