"use client"

import { useMemo, useState } from "react"
import Link from "next/link"
import { ArrowDownRight, ArrowUpRight, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import type { GrowthLead } from "@/app/actions/growth-actions"

const funnels = ["FORMULÁRIO", "QUIZ", "VÉRTEBRA"] as const
type FunnelName = (typeof funnels)[number]
type Period = "today" | "7" | "30" | "90" | "month" | "previous"
type CompareMode = "volume" | "advance" | "losses" | "result"
const funnelLinks: Record<FunnelName, string> = { FORMULÁRIO: "/qualificacao", QUIZ: "/funil", "VÉRTEBRA": "/zona-de-execucao/funil-vertebra" }
const lossTerms = ["perdido", "perdida", "lost"]
const closedTerms = ["fechado", "fechada", "ganho", "ganha", "closed"]
const advanceTerms: Record<FunnelName, string[]> = { FORMULÁRIO: ["proposta enviada"], QUIZ: ["alto potencial"], "VÉRTEBRA": ["contato feito"] }

function isTerm(value: string, terms: string[]) { const normalized = value.toLowerCase(); return terms.some((term) => normalized.includes(term)) }
function pct(value: number, total: number) { return total > 0 ? `${((value / total) * 100).toFixed(1)}%` : "—" }
function change(current: number, previous: number, suffix = "%") { if (!previous) return null; const value = ((current - previous) / previous) * 100; return `${value >= 0 ? "+" : ""}${value.toFixed(1)}${suffix}` }
function range(period: Period) { const end = new Date(); const start = new Date(end); if (period === "today") start.setHours(0, 0, 0, 0); else if (period === "month") start.setDate(1); else if (period === "previous") { const month = new Date(end.getFullYear(), end.getMonth() - 1, 1); return { start: month, end: new Date(end.getFullYear(), end.getMonth(), 1) } } else start.setTime(end.getTime() - Number(period) * 86400000); return { start, end } }
function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()) }

export function FunisGrowthDashboard({ initialLeads }: { initialLeads: GrowthLead[] }) {
  const [source, setSource] = useState("Todos")
  const [period, setPeriod] = useState<Period>("30")
  const [mode, setMode] = useState<CompareMode>("volume")
  const sources = useMemo(() => Array.from(new Set(initialLeads.map((lead) => lead.source))).filter(Boolean).sort(), [initialLeads])
  const { current, previous } = useMemo(() => { const selected = range(period); const duration = selected.end.getTime() - selected.start.getTime(); const matches = (lead: GrowthLead, from: Date, to: Date) => lead.source === source || source === "Todos" ? new Date(lead.createdAt) >= from && new Date(lead.createdAt) < to : false; return { current: initialLeads.filter((lead) => matches(lead, selected.start, selected.end)), previous: initialLeads.filter((lead) => matches(lead, new Date(selected.start.getTime() - duration), selected.start)) } }, [initialLeads, period, source])
  const stats = useMemo(() => funnels.map((name) => { const leads = current.filter((lead) => lead.funnel === name); const prior = previous.filter((lead) => lead.funnel === name); const advance = leads.filter((lead) => isTerm(lead.stage, advanceTerms[name])); const priorAdvance = prior.filter((lead) => isTerm(lead.stage, advanceTerms[name])); const losses = leads.filter((lead) => isTerm(lead.stage, lossTerms)); const priorLosses = prior.filter((lead) => isTerm(lead.stage, lossTerms)); const closed = leads.filter((lead) => isTerm(lead.stage, closedTerms)); const result = name === "QUIZ" ? advance : closed; const stages = Array.from(new Set(leads.map((lead) => lead.stage))).map((stage) => ({ stage, count: leads.filter((lead) => lead.stage === stage).length })).sort((a, b) => b.count - a.count); return { name, leads, prior, advance, priorAdvance, losses, priorLosses, closed, result, stages } }), [current, previous])
  const total = current.length
  const clear = () => { setSource("Todos"); setPeriod("30"); setMode("volume") }
  const compareValue = (item: typeof stats[number]) => mode === "volume" ? item.leads.length : mode === "advance" ? item.advance.length / Math.max(1, item.leads.length) * 100 : mode === "losses" ? item.losses.length / Math.max(1, item.leads.length) * 100 : item.result.length
  const changes = stats.flatMap((item) => { const volume = change(item.leads.length, item.prior.length); const advance = item.leads.length && item.prior.length ? `${((item.advance.length / item.leads.length - item.priorAdvance.length / item.prior.length) * 100).toFixed(1)} p.p.` : null; const losses = item.leads.length && item.prior.length ? `${((item.losses.length / item.leads.length - item.priorLosses.length / item.prior.length) * 100).toFixed(1)} p.p.` : null; return [{ name: item.name, label: "Volume", value: volume, score: volume ? Math.abs(Number.parseFloat(volume)) : 0 }, { name: item.name, label: "Principal avanço", value: advance, score: advance ? Math.abs(Number.parseFloat(advance)) : 0 }, { name: item.name, label: "Perdas", value: losses, score: losses ? Math.abs(Number.parseFloat(losses)) : 0 }] }).filter((item) => item.value && item.score >= 1).sort((a, b) => b.score - a.score).slice(0, 4)

  return <div className="space-y-6">
    <header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Funis Growth</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Funis Growth</h1><p className="mt-2 text-muted-foreground">Performance dos seus funis.</p></div><Button variant="outline" onClick={clear}><X className="mr-2 size-4" />Limpar filtros</Button></header>
    <section className="grid gap-3 rounded-xl border border-border bg-card p-4 md:grid-cols-3"><label className="grid gap-2 text-sm text-muted-foreground">Período<select className="h-10 rounded-md border border-input bg-background px-3 text-foreground" value={period} onChange={(event) => setPeriod(event.target.value as Period)}><option value="today">Hoje</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option><option value="month">Este mês</option><option value="previous">Mês anterior</option></select></label><label className="grid gap-2 text-sm text-muted-foreground">utm_campaign<select className="h-10 rounded-md border border-input bg-background px-3 text-foreground" value={source} onChange={(event) => setSource(event.target.value)}><option>Todos</option>{sources.map((item) => <option key={item}>{item}</option>)}</select></label><div className="flex items-end text-sm text-muted-foreground">Comparação automática com o período anterior equivalente.</div></section>
    <section><h2 className="mb-3 text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">Comparativo dos funis</h2><div className="overflow-x-auto rounded-xl border border-border bg-card"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-border text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Métrica</th>{stats.map((item) => <th key={item.name} className="px-5 py-3 font-medium">{item.name}</th>)}</tr></thead><tbody>{<><tr className="border-b border-border/60"><td className="px-5 py-3 font-medium">Leads</td>{stats.map((item) => <td key={item.name} className="px-5 py-3"><strong>{item.leads.length}</strong>{change(item.leads.length, item.prior.length) && <Trend value={change(item.leads.length, item.prior.length)!} />}</td>)}</tr><tr className="border-b border-border/60"><td className="px-5 py-3 font-medium">% do volume</td>{stats.map((item) => <td key={item.name} className="px-5 py-3 text-muted-foreground">{pct(item.leads.length, total)}</td>)}</tr><tr className="border-b border-border/60"><td className="px-5 py-3 font-medium">Principal avanço</td>{stats.map((item) => <td key={item.name} className="px-5 py-3"><strong>{pct(item.advance.length, item.leads.length)}</strong><span className="block text-xs text-muted-foreground">{label(advanceTerms[item.name][0])}</span></td>)}</tr><tr className="border-b border-border/60"><td className="px-5 py-3 font-medium">Resultado</td>{stats.map((item) => <td key={item.name} className="px-5 py-3 text-muted-foreground">{item.name === "QUIZ" ? `${item.result.length} Alto Potencial` : `${item.result.length} fechado${item.result.length === 1 ? "" : "s"}`}</td>)}</tr><tr className="border-b border-border/60"><td className="px-5 py-3 font-medium">Perdas</td>{stats.map((item) => <td key={item.name} className="px-5 py-3 text-muted-foreground">{item.losses.length || item.priorLosses.length ? `${item.losses.length} · ${pct(item.losses.length, item.leads.length)}` : "—"}</td>)}</tr><tr><td className="px-5 py-3 font-medium">Operação</td>{stats.map((item) => <td key={item.name} className="px-5 py-3"><Link className="text-primary hover:underline" href={funnelLinks[item.name]}>Ver funil →</Link></td>)}</tr></>}</tbody></table></div></section>
    <section><h2 className="mb-3 text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">Raio-X dos funis</h2><div className="grid gap-4 lg:grid-cols-3">{stats.map((item) => <div key={item.name} className="rounded-xl border border-border bg-card p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">{item.name}</h3><span className="text-xl font-semibold">{item.leads.length}</span></div><p className="text-xs text-muted-foreground">entradas</p><div className="mt-4 space-y-2">{item.stages.length ? item.stages.map((stage) => <div key={stage.stage} className="flex items-center justify-between rounded-lg bg-muted/50 px-3 py-2 text-sm"><span>{stage.count} {label(stage.stage)}</span><span className="text-muted-foreground">{pct(stage.count, item.leads.length)}</span></div>) : <p className="text-sm text-muted-foreground">Sem dados no período.</p>}</div><Link className="mt-4 inline-block text-sm text-primary hover:underline" href={funnelLinks[item.name]}>Ver funil →</Link></div>)}</div></section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">O que mudou?</h2><div className="mt-4 space-y-2">{changes.length ? changes.map((item) => <div key={`${item.name}-${item.label}`} className="flex items-center justify-between rounded-lg border border-border px-3 py-2 text-sm"><span><strong>{item.name}</strong> · {item.label}</span><span className={item.value?.startsWith("-") ? "text-destructive" : "text-emerald-500"}>{item.value}</span></div>) : <p className="text-sm text-muted-foreground">Nenhuma mudança relevante identificada no período.</p>}</div></div><div className="rounded-xl border border-border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Comparar</h2><div className="flex flex-wrap gap-2">{(["volume", "advance", "losses", "result"] as CompareMode[]).map((item) => <Button key={item} size="sm" variant={mode === item ? "default" : "outline"} onClick={() => setMode(item)}>{item === "volume" ? "Volume" : item === "advance" ? "Principal avanço" : item === "losses" ? "Perdas" : "Resultado"}</Button>)}</div></div><div className="mt-5 space-y-3">{stats.map((item) => <div key={item.name}><div className="mb-1 flex justify-between text-sm"><span>{item.name}</span><strong>{mode === "volume" || mode === "result" ? compareValue(item) : `${compareValue(item).toFixed(1)}%`}</strong></div><div className="h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{ width: `${Math.min(100, mode === "volume" ? total ? compareValue(item) / total * 100 : 0 : compareValue(item))}%` }} /></div></div>)}</div></div></section>
  </div>
}

function Trend({ value }: { value: string }) { const negative = value.startsWith("-"); return <span className={`ml-2 inline-flex items-center text-xs ${negative ? "text-destructive" : "text-emerald-500"}`}>{negative ? <ArrowDownRight className="size-3" /> : <ArrowUpRight className="size-3" />}{value}</span> }
