"use client"

import { useMemo, useState } from "react"
import Link from "next/link"
import { ArrowDownRight, ArrowUpRight, BarChart3, CircleHelp, Filter, Target, TrendingUp, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import type { GrowthLead } from "@/app/actions/growth-actions"

const funnels = ["CRM", "QUIZ", "VÉRTEBRA"] as const
type FunnelName = (typeof funnels)[number]
type Period = "today" | "7" | "30" | "90" | "month" | "previous"
type Dimension = "conversion" | "quality" | "volume" | "capital" | "speed" | "losses"

const funnelLinks: Record<FunnelName, string> = { CRM: "/crm", QUIZ: "/funil", "VÉRTEBRA": "/zona-de-execucao/funil-vertebra" }
const lossTerms = ["perdido", "perdida", "lost"]
const closedTerms = ["fechado", "fechada", "ganho", "ganha", "closed"]

function pct(value: number, total: number) { return total > 0 ? `${((value / total) * 100).toFixed(1)}%` : "—" }
function signedPct(current: number, previous: number) { if (!previous) return "—"; const change = ((current - previous) / previous) * 100; return `${change >= 0 ? "+" : ""}${change.toFixed(1)}%` }
function isTerm(value: string, terms: string[]) { const normalized = value.toLowerCase(); return terms.some((term) => normalized.includes(term)) }
function periodRange(period: Period) { const now = new Date(); const end = new Date(now); let start = new Date(now); if (period === "today") start.setHours(0, 0, 0, 0); else if (period === "month") start = new Date(now.getFullYear(), now.getMonth(), 1); else if (period === "previous") { start = new Date(now.getFullYear(), now.getMonth() - 1, 1); return { start, end: new Date(now.getFullYear(), now.getMonth(), 1) } } else start = new Date(now.getTime() - Number(period) * 86400000); return { start, end } }
function labelStage(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()) }

export function FunisGrowthDashboard({ initialLeads }: { initialLeads: GrowthLead[] }) {
  const [funnel, setFunnel] = useState<"Todos" | FunnelName>("Todos")
  const [source, setSource] = useState("Todos")
  const [period, setPeriod] = useState<Period>("30")
  const [dimension, setDimension] = useState<Dimension>("conversion")
  const sources = useMemo(() => Array.from(new Set(initialLeads.map((lead) => lead.source))).filter(Boolean).sort(), [initialLeads])
  const { current, previous } = useMemo(() => { const range = periodRange(period); const duration = range.end.getTime() - range.start.getTime(); return { current: initialLeads.filter((lead) => (funnel === "Todos" || lead.funnel === funnel) && (source === "Todos" || lead.source === source) && new Date(lead.createdAt) >= range.start && new Date(lead.createdAt) < range.end), previous: initialLeads.filter((lead) => { const created = new Date(lead.createdAt).getTime(); return created >= range.start.getTime() - duration && created < range.start.getTime() && (funnel === "Todos" || lead.funnel === funnel) && (source === "Todos" || lead.source === source) }) } }, [initialLeads, funnel, source, period])
  const stats = useMemo(() => funnels.map((name) => { const leads = current.filter((lead) => lead.funnel === name); const prior = previous.filter((lead) => lead.funnel === name); const qualified = leads.filter((lead) => name === "QUIZ" ? Boolean(lead.profile && !isTerm(lead.profile, ["baixa", "não", "nao"])) : !isTerm(lead.stage, ["novo", "captado"])); const losses = leads.filter((lead) => isTerm(lead.stage, lossTerms)); const closed = leads.filter((lead) => isTerm(lead.stage, closedTerms)); const quality = name === "QUIZ" ? qualified.length : qualified.length; return { name, leads, prior, qualified, losses, closed, quality, stages: Array.from(new Set(leads.map((lead) => lead.stage))).map((stage) => ({ stage, count: leads.filter((lead) => lead.stage === stage).length })).sort((a, b) => b.count - a.count) } }), [current, previous])
  const totalQualified = stats.reduce((sum, item) => sum + item.qualified.length, 0)
  const totalLosses = stats.reduce((sum, item) => sum + item.losses.length, 0)
  const totalClosed = stats.reduce((sum, item) => sum + item.closed.length, 0)
  const priorQualified = previous.filter((lead) => !isTerm(lead.stage, ["novo", "captado"])).length
  const largest = [...stats].sort((a, b) => b.leads.length - a.leads.length)[0]
  const attention = [...stats].sort((a, b) => b.losses.length - a.losses.length)[0]
  const clear = () => { setFunnel("Todos"); setSource("Todos"); setPeriod("30"); setDimension("conversion") }
  const metric = (item: typeof stats[number]) => dimension === "volume" ? item.leads.length : dimension === "quality" ? pct(item.quality, item.leads.length) : dimension === "losses" ? pct(item.losses.length, item.leads.length) : dimension === "conversion" ? pct(item.closed.length, item.leads.length) : "—"

  return <div className="space-y-8">
    <header className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Growth intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Funis Growth</h1><p className="mt-2 text-muted-foreground">Inteligência e performance dos seus funis.</p></div><Button variant="outline" onClick={clear}><X className="mr-2 size-4" />Limpar filtros</Button></header>
    <section className="grid gap-3 rounded-xl border border-border bg-card p-4 md:grid-cols-3"><label className="grid gap-2 text-sm text-muted-foreground">Período<select className="h-10 rounded-md border border-input bg-background px-3 text-foreground" value={period} onChange={(event) => setPeriod(event.target.value as Period)}><option value="today">Hoje</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option><option value="month">Este mês</option><option value="previous">Mês anterior</option></select></label><label className="grid gap-2 text-sm text-muted-foreground">Funil<select className="h-10 rounded-md border border-input bg-background px-3 text-foreground" value={funnel} onChange={(event) => setFunnel(event.target.value as "Todos" | FunnelName)}><option value="Todos">Todos os funis</option>{funnels.map((item) => <option key={item}>{item}</option>)}</select></label><label className="grid gap-2 text-sm text-muted-foreground">Origem / UTM<select className="h-10 rounded-md border border-input bg-background px-3 text-foreground" value={source} onChange={(event) => setSource(event.target.value)}><option>Todos</option>{sources.map((item) => <option key={item}>{item}</option>)}</select></label></section>
    <section><div className="mb-4"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">Visão do período</p><h2 className="mt-1 text-xl font-semibold">Os números que importam</h2></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><MetricCard label="Leads captados" value={current.length} comparison={signedPct(current.length, previous.length)} icon={BarChart3} /><MetricCard label="Taxa de qualificação" value={pct(totalQualified, current.length)} comparison={signedPct(totalQualified, priorQualified)} icon={Target} /><MetricCard label="Taxa de avanço" value={pct(current.length - totalLosses, current.length)} comparison="Dados disponíveis por etapa" icon={TrendingUp} /><MetricCard label="Taxa de fechamento" value={pct(totalClosed, current.length)} comparison={totalClosed ? "Baseada em status de fechamento" : "Sem fechamentos registrados"} icon={Filter} /></div></section>
    <section className="rounded-xl border border-primary/30 bg-primary/5 p-6"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Growth intelligence</p><h2 className="mt-1 text-xl font-semibold">O que os dados estão mostrando</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><Insight title="Maior volume" text={largest?.leads.length ? `${pct(largest.leads.length, current.length)} dos leads do período estão no funil ${largest.name}.` : "Dados insuficientes no período selecionado."} /><Insight title="Qualidade" text={current.length ? `${pct(totalQualified, current.length)} dos leads possuem sinal de qualificação disponível.` : "Dados insuficientes no período selecionado."} /><Insight title="Ponto de atenção" text={attention?.losses.length ? `${attention.losses.length} leads do funil ${attention.name} estão classificados como perda.` : "Nenhuma perda classificada no período selecionado."} /></div></section>
    <section><div className="mb-4"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">Comparação estratégica</p><h2 className="mt-1 text-xl font-semibold">Comparativo dos funis</h2></div><div className="overflow-x-auto rounded-xl border border-border bg-card"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-border text-muted-foreground"><tr><th className="px-5 py-4 font-medium">Métrica</th>{stats.map((item) => <th key={item.name} className="px-5 py-4 font-medium">{item.name}</th>)}</tr></thead><tbody>{[["Leads", (item: typeof stats[number]) => item.leads.length], ["% do volume", (item: typeof stats[number]) => pct(item.leads.length, current.length)], ["Qualificação", (item: typeof stats[number]) => pct(item.quality, item.leads.length)], ["Avanço", (item: typeof stats[number]) => pct(item.leads.length - item.losses.length, item.leads.length)], ["Perda", (item: typeof stats[number]) => pct(item.losses.length, item.leads.length)], ["Fechamento", (item: typeof stats[number]) => pct(item.closed.length, item.leads.length)]].map(([label, getter]) => <tr key={String(label)} className="border-b border-border/60 last:border-0"><td className="px-5 py-4 font-medium">{String(label)}</td>{stats.map((item) => <td key={item.name} className="px-5 py-4 text-muted-foreground">{(getter as (item: typeof stats[number]) => string | number)(item)}</td>)}</tr>)}<tr><td className="px-5 py-4 font-medium">Operação</td>{stats.map((item) => <td key={item.name} className="px-5 py-4"><Link className="text-primary hover:underline" href={funnelLinks[item.name]}>Ver funil →</Link></td>)}</tr></tbody></table></div></section>
    <section><div className="mb-4"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">Etapas reais de cada operação</p><h2 className="mt-1 text-xl font-semibold">Jornada dos funis</h2></div><div className="grid gap-4 lg:grid-cols-3">{stats.map((item) => <div key={item.name} className="rounded-xl border border-border bg-card p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">{item.name}</h3><span className="text-2xl font-semibold">{item.leads.length}</span></div><p className="mt-1 text-sm text-muted-foreground">registros captados</p><div className="mt-5 space-y-2">{item.stages.length ? item.stages.map((stage) => <div key={stage.stage} className="flex items-center justify-between rounded-lg bg-muted/50 px-3 py-2 text-sm"><span>{labelStage(stage.stage)}</span><strong>{stage.count}</strong></div>) : <p className="text-sm text-muted-foreground">Dados insuficientes.</p>}</div></div>)}</div></section>
    <section className="rounded-xl border border-border bg-card p-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">Análise orientada por dados</p><h2 className="mt-1 text-xl font-semibold">Eficiência dos funis</h2></div><div className="flex flex-wrap gap-2">{(["conversion", "quality", "volume", "capital", "speed", "losses"] as Dimension[]).map((item) => <Button key={item} size="sm" variant={dimension === item ? "default" : "outline"} onClick={() => setDimension(item)}>{item === "conversion" ? "Conversão" : item === "quality" ? "Qualidade" : item === "volume" ? "Volume" : item === "capital" ? "Capital" : item === "speed" ? "Velocidade" : "Perdas"}</Button>)}</div></div><div className="mt-6 grid gap-4 md:grid-cols-3">{stats.map((item) => <div key={item.name} className="rounded-lg border border-border p-4"><div className="flex justify-between"><span className="font-medium">{item.name}</span><span className="text-2xl font-semibold">{metric(item)}</span></div><div className="mt-3 h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{ width: `${dimension === "volume" ? Math.min(100, current.length ? item.leads.length / current.length * 100 : 0) : Math.min(100, item.leads.length ? item.quality / item.leads.length * 100 : 0)}%` }} /></div></div>)}</div>{dimension === "capital" || dimension === "speed" ? <p className="mt-5 text-sm text-muted-foreground">Não há campos confiáveis disponíveis nos três funis para comparar {dimension === "capital" ? "capital" : "velocidade"} sem inventar equivalências.</p> : null}</section>
    <section className="grid gap-6 lg:grid-cols-2"><InsightPanel title="Onde estamos perdendo?" items={stats.map((item) => `${item.name}: ${item.losses.length ? `${item.losses.length} perdas (${pct(item.losses.length, item.leads.length)})` : "nenhuma perda classificada"}`)} /><InsightPanel title="Qualidade dos leads" items={stats.map((item) => `${item.name}: ${item.quality ? `${item.quality} sinais qualificados (${pct(item.quality, item.leads.length)})` : "sem classificação comparável"}`)} /></section>
  </div>
}

function MetricCard({ label, value, comparison, icon: Icon }: { label: string; value: string | number; comparison: string; icon: typeof BarChart3 }) { return <div className="rounded-xl border border-border bg-card p-5"><Icon className="size-5 text-primary" /><p className="mt-5 text-sm text-muted-foreground">{label}</p><p className="mt-1 text-3xl font-semibold">{value}</p><p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground">{comparison.startsWith("+") ? <ArrowUpRight className="size-3 text-emerald-500" /> : comparison.startsWith("-") ? <ArrowDownRight className="size-3 text-destructive" /> : null}{comparison}</p></div> }
function Insight({ title, text }: { title: string; text: string }) { return <div className="rounded-lg border border-border/70 bg-background/50 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-primary">{title}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div> }
function InsightPanel({ title, items }: { title: string; items: string[] }) { return <section className="rounded-xl border border-border bg-card p-6"><div className="flex items-center gap-2"><h2 className="text-lg font-semibold">{title}</h2><CircleHelp className="size-4 text-muted-foreground" /></div><div className="mt-5 space-y-3">{items.map((item) => <div key={item} className="rounded-lg border border-border px-4 py-3 text-sm text-muted-foreground">{item}</div>)}</div></section> }
