"use client"

import { useMemo, useState, useTransition } from "react"
import { ArrowRight, Check, Copy, Plus, Search, Trash2, X } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { cn } from "@/lib/utils"
import { createProposalLead, deleteProposalLead, updateProposalLead, type ProposalLead, type ProposalStage } from "@/app/actions/propostas-crm-actions"
import { firstName, proposalLink, propostaConfig } from "@/lib/proposta-config"

const columns:{key:ProposalStage;label:string; tone:string}[] = [{key:"reunioes",label:"Reuniões Realizadas",tone:"border-border"},{key:"follow1",label:"Follow 1",tone:"border-primary/40"},{key:"follow2",label:"Follow 2",tone:"border-primary/50"},{key:"follow3",label:"Follow 3",tone:"border-primary/60"},{key:"win",label:"Win",tone:"border-emerald-500/60"},{key:"loss",label:"Loss",tone:"border-rose-500/40"}]
const daysAgo=(date:string)=>Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/86400000))

export function PropostasCRM({initialLeads}:{initialLeads:ProposalLead[]}) {
 const [leads,setLeads]=useState(initialLeads); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<ProposalLead|null>(null); const [creating,setCreating]=useState(false); const [draftName,setDraftName]=useState(""); const [saving,startSaving]=useTransition()
 const visible=useMemo(()=>leads.filter(l=>l.nome.toLowerCase().includes(query.toLowerCase())),[leads,query])
 const save=(data:Partial<ProposalLead>)=>{ if(!selected)return; const next={...selected,...data}; setSelected(next); setLeads(ls=>ls.map(l=>l.id===next.id?next:l)); startSaving(async()=>{await updateProposalLead(next.id,data)}) }
 const add=()=>{if(!draftName.trim())return; startSaving(async()=>{const lead=await createProposalLead(draftName,new Date().toISOString().slice(0,10));setLeads(ls=>[...ls,lead]);setSelected(lead);setCreating(false);setDraftName("")})}
 const move=(lead:ProposalLead,stage:ProposalStage)=>{setLeads(ls=>ls.map(l=>l.id===lead.id?{...l,etapa:stage}:l));startSaving(async()=>{await updateProposalLead(lead.id,{etapa:stage})})}
 return <div className="flex flex-col gap-5"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">CRM de propostas</p><h2 className="text-2xl font-bold">Acompanhe cada decisão</h2><p className="text-sm text-muted-foreground">Registre a reunião, faça follow-ups e marque o resultado.</p></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="w-full pl-9 sm:w-64" placeholder="Buscar lead" value={query} onChange={e=>setQuery(e.target.value)}/></div><Button onClick={()=>setCreating(true)}><Plus data-icon="inline-start"/> Novo lead</Button></div></div><div className="flex gap-3 overflow-x-auto pb-3">{columns.map(col=><section key={col.key} className={cn("flex min-h-[420px] w-[280px] shrink-0 flex-col rounded-2xl border bg-card/30",col.tone)}><header className="flex items-center justify-between border-b p-3"><span className="text-sm font-semibold">{col.label}</span><Badge variant="outline">{visible.filter(l=>l.etapa===col.key).length}</Badge></header><div className="flex flex-1 flex-col gap-2 p-3">{visible.filter(l=>l.etapa===col.key).map(lead=><article key={lead.id} draggable onDragStart={e=>e.dataTransfer.setData("lead",String(lead.id))} onDragOver={e=>e.preventDefault()} onDrop={e=>{const found=leads.find(l=>l.id===Number(e.dataTransfer.getData("lead")));if(found)move(found,col.key)}} onClick={()=>setSelected(lead)} className="cursor-pointer rounded-xl border border-border/60 bg-card p-3 transition hover:border-primary/50"><div className="flex items-start justify-between gap-2"><strong className="text-sm">{lead.nome}</strong><ArrowRight className="size-4 text-muted-foreground"/></div><p className="mt-1 text-xs text-muted-foreground">Reunião há {daysAgo(lead.data_reuniao)} dias</p><div className="mt-3 flex gap-1">{[lead.follow1_enviado,lead.follow2_enviado,lead.follow3_enviado].map((done,i)=><span key={i} className={cn("size-2 rounded-full",done?"bg-primary":"bg-muted")} />)}</div>{lead.anotacoes&&<p className="mt-3 line-clamp-2 text-xs text-muted-foreground">{lead.anotacoes}</p>}<div className="mt-3 md:hidden"><Select value={lead.etapa} onValueChange={value=>move(lead,value as ProposalStage)}><SelectTrigger className="h-8 text-xs"><SelectValue placeholder="Mover para"/></SelectTrigger><SelectContent>{columns.map(c=><SelectItem key={c.key} value={c.key}>{c.label}</SelectItem>)}</SelectContent></Select></div></article>)}{!visible.some(l=>l.etapa===col.key)&&<p className="py-8 text-center text-xs text-muted-foreground">Nenhum lead nesta etapa.</p>}</div></section>)}</div>
 <Dialog open={creating} onOpenChange={setCreating}><DialogContent><DialogHeader><DialogTitle>Novo lead</DialogTitle></DialogHeader><div className="flex flex-col gap-4"><Input autoFocus placeholder="Nome do lead" value={draftName} onChange={e=>setDraftName(e.target.value)}/><Button onClick={add} disabled={saving}>Criar lead</Button></div></DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={open=>!open&&setSelected(null)}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{selected?.nome}</DialogTitle></DialogHeader>{selected&&<LeadEditor lead={selected} save={save} onDelete={()=>{startSaving(async()=>{await deleteProposalLead(selected.id);setLeads(ls=>ls.filter(l=>l.id!==selected.id));setSelected(null)})}}/>}</DialogContent></Dialog></div>
}

function LeadEditor({lead,save,onDelete}:{lead:ProposalLead;save:(data:Partial<ProposalLead>)=>void;onDelete:()=>void}){const [copied,setCopied]=useState("");const copy=async(text:string,key:string)=>{await navigator.clipboard.writeText(text);setCopied(key);setTimeout(()=>setCopied(""),1500)};return <div className="flex flex-col gap-5"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Nome<Input className="mt-1" value={lead.nome} onChange={e=>save({nome:e.target.value})}/></label><label className="text-sm">Data da reunião<Input className="mt-1" type="date" value={lead.data_reuniao.slice(0,10)} onChange={e=>save({data_reuniao:e.target.value})}/></label></div>{[1,2,3].map(n=>{const msg=lead[`follow${n}_mensagem` as keyof ProposalLead] as string;const sent=lead[`follow${n}_enviado` as keyof ProposalLead] as boolean;return <div key={n} className="rounded-xl border p-3"><div className="mb-2 flex items-center justify-between"><span className="text-sm font-semibold">Follow {n}</span><Button variant={sent?"secondary":"outline"} size="sm" onClick={()=>save({[`follow${n}_enviado`]:!sent,[`follow${n}_data`]:!sent?new Date().toISOString().slice(0,10):null})}>{sent?<Check data-icon="inline-start"/>:null}{sent?"Enviado":"Marcar enviado"}</Button></div><Textarea value={msg} onChange={e=>save({[`follow${n}_mensagem`]:e.target.value})}/><Button variant="ghost" size="sm" className="mt-2" onClick={()=>copy(msg,`f${n}`)}>{copied===`f${n}`?<Check data-icon="inline-start"/>:<Copy data-icon="inline-start"/>}{copied===`f${n}`?"Copiado":"Copiar"}</Button></div>})}<label className="text-sm">Anotações<Textarea className="mt-1 min-h-28" value={lead.anotacoes} onChange={e=>save({anotacoes:e.target.value})}/></label><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>copy(proposalLink(lead.nome),"link")}>{copied==="link"?<Check data-icon="inline-start"/>:<Copy data-icon="inline-start"/>}{copied==="link"?"Copiado":"Copiar link da proposta"}</Button>{lead.etapa==="win"&&<Select value={lead.plano_fechado||""} onValueChange={value=>save({plano_fechado:value})}><SelectTrigger className="w-56"><SelectValue placeholder="Plano fechado"/></SelectTrigger><SelectContent>{propostaConfig.planos.map(p=><SelectItem key={p.nome} value={p.nome}>{p.nome}</SelectItem>)}</SelectContent></Select>}</div>{lead.etapa==="loss"&&<Input placeholder="Motivo da perda" value={lead.motivo_loss||""} onChange={e=>save({motivo_loss:e.target.value})}/>}<Button variant="destructive" className="self-start" onClick={onDelete}><Trash2 data-icon="inline-start"/> Excluir lead</Button></div>}
