"use client"

import { useState, useTransition } from "react"
import Link from "next/link"
import { ArrowLeft, Check, Copy, Eye, EyeOff, GripVertical, Plus, Save, Settings2, Trash2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Badge } from "@/components/ui/badge"
import { updateMarket, updateSection, createSection, deleteSection, duplicateMarket, archiveMarket, type Market, type MarketSection } from "@/app/actions/market-guide-actions"

export function MarketGuideDetail({ initial, isAdmin }: { initial: { market: Market; sections: MarketSection[] }; isAdmin: boolean }) {
  const [market, setMarket] = useState(initial.market); const [sections, setSections] = useState(initial.sections); const [editing, setEditing] = useState(false); const [pending, startTransition] = useTransition(); const [copied, setCopied] = useState("")
  function copy(value: string, key: string) { navigator.clipboard.writeText(value); setCopied(key); setTimeout(() => setCopied(""), 1200) }
  function saveSection(section: MarketSection, content: Record<string, unknown>, title = section.title, visible = section.visible) { startTransition(async () => { await updateSection(section.id, { title, content, visible }); setSections((items) => items.map((s) => s.id === section.id ? { ...s, title, content, visible } : s)) }) }
  function saveMarket(form: HTMLFormElement) { const data = new FormData(form); startTransition(async () => { const r = await updateMarket(market.id, { name: String(data.get("name")), flag: String(data.get("flag")), language: String(data.get("language")), currency: String(data.get("currency")) }); setMarket({ ...market, name: String(data.get("name")), flag: String(data.get("flag")), language: String(data.get("language")), currency: String(data.get("currency")), slug: r.slug }); setEditing(false); window.history.replaceState(null, "", `/guia-de-mercados/${r.slug}`) }) }
  return <main className="min-h-screen bg-background p-6 lg:p-10"><div className="mx-auto max-w-6xl"><Link href="/guia-de-mercados" className="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Voltar aos mercados</Link><header className="mb-8 flex flex-wrap items-start justify-between gap-5"><div className="flex items-start gap-4"><span className="text-5xl">{market.flag}</span><div><h1 className="text-3xl font-semibold">{market.name}</h1><p className="mt-2 text-muted-foreground">{market.language} · {market.currency}</p><p className="mt-1 text-xs text-muted-foreground">Atualizado em {new Date(market.updated_at).toLocaleDateString("pt-BR")} por {market.updated_by_name || "Admin"}</p></div></div>{isAdmin && <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setEditing(!editing)}><Settings2 data-icon="inline-start" />{editing ? "Fechar edição" : "Editar"}</Button><Button variant="outline" onClick={() => startTransition(async () => { const r = await duplicateMarket(market.id); if (r.slug) window.location.href = `/guia-de-mercados/${r.slug}` })}><Copy data-icon="inline-start" />Duplicar</Button><Button variant="outline" onClick={() => startTransition(async () => { await archiveMarket(market.id); window.location.href = "/guia-de-mercados" })}>Arquivar</Button></div>}</header>
  {editing && <form onSubmit={(e) => {e.preventDefault(); saveMarket(e.currentTarget)}} className="mb-8 grid gap-3 rounded-xl border border-primary/30 bg-card p-4 sm:grid-cols-2"><Input name="name" defaultValue={market.name} placeholder="Nome" required /><Input name="flag" defaultValue={market.flag} placeholder="Bandeira" /><Input name="language" defaultValue={market.language} placeholder="Idioma" required /><Input name="currency" defaultValue={market.currency} placeholder="Moeda" required /><Button className="sm:col-span-2" disabled={pending}><Save data-icon="inline-start" />Salvar mercado</Button></form>}
  {isAdmin && editing && <Button variant="outline" className="mb-5" onClick={() => startTransition(async () => { await createSection(market.id, { title: "Nova seção", sectionType: "text" }); window.location.reload() })}><Plus data-icon="inline-start" />Adicionar seção</Button>}
  <div className="flex flex-col gap-5">{sections.map((section) => <SectionEditor key={section.id} section={section} editable={isAdmin && editing} copied={copied} onCopy={copy} onSave={saveSection} onDelete={() => startTransition(async () => { await deleteSection(section.id); setSections((s) => s.filter((x) => x.id !== section.id)) })} />)}</div>
  </div></main>
}
function SectionEditor({ section, editable, copied, onCopy, onSave, onDelete }: { section: MarketSection; editable: boolean; copied: string; onCopy: (v:string,k:string)=>void; onSave: (s:MarketSection,c:Record<string,unknown>,t?:string,v?:boolean)=>void; onDelete:()=>void }) {
  const [title, setTitle] = useState(section.title); const [content, setContent] = useState(JSON.stringify(section.content, null, 2)); const [visible, setVisible] = useState(section.visible); const value = section.content.text ? String(section.content.text) : Object.values(section.content).join("\n")
  return <section className={`${section.visible ? "" : "opacity-50"} rounded-xl border border-border bg-card p-5`}><div className="mb-4 flex items-start justify-between gap-3"><div className="flex items-center gap-2"><GripVertical className="size-4 text-muted-foreground" /><h2 className="text-lg font-semibold">{editable ? <Input value={title} onChange={(e)=>setTitle(e.target.value)} /> : section.title}</h2></div>{editable && <div className="flex gap-1"><Button size="icon" variant="ghost" title="Mostrar/ocultar" onClick={()=>{setVisible(!visible);onSave(section, section.content, title, !visible)}}>{visible ? <Eye className="size-4"/>:<EyeOff className="size-4"/>}</Button><Button size="icon" variant="ghost" title="Excluir" onClick={onDelete}><Trash2 className="size-4"/></Button></div>}</div>{editable ? <div className="flex flex-col gap-3"><Textarea value={content} onChange={(e)=>setContent(e.target.value)} rows={8} className="font-mono text-xs" /><Button onClick={()=>{try{onSave(section,JSON.parse(content),title,visible)}catch{}}} disabled={!content}><Save data-icon="inline-start"/>Salvar seção</Button></div> : <RenderContent section={section} value={value} copied={copied} onCopy={onCopy} />}</section>
}
function RenderContent({ section, value, copied, onCopy }: { section: MarketSection; value: string; copied: string; onCopy:(v:string,k:string)=>void }) { if (!value) return <p className="text-sm italic text-muted-foreground">Não preenchido.</p>; if (section.section_type === "table" && Array.isArray(section.content.rows)) return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><tbody>{(section.content.rows as Record<string,string>[]).map((row,i)=><tr key={i} className="border-b border-border"><td className="py-3 font-medium">{Object.values(row)[0]}</td><td className="py-3 text-muted-foreground">{Object.values(row).slice(1).join(" · ")}</td><td className="py-3 text-right"><Button size="icon" variant="ghost" onClick={()=>onCopy(Object.values(row).join(" | "),String(i))}>{copied===String(i)?<Check className="size-4"/>:<Copy className="size-4"/>}</Button></td></tr>)}</tbody></table></div>; return <div className="whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{value}<Button size="icon" variant="ghost" className="ml-2 inline-flex" onClick={()=>onCopy(value, String(section.id))}>{copied===String(section.id)?<Check className="size-4"/>:<Copy className="size-4"/>}</Button></div> }
